# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: umsgpack build and test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x', '1.22.x']
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Set up Go ${{matrix.go-version}}
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.go-version}}
    - name: Display Go version
      run: go version
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Check format
      run: make checkformat
    - name: Vet
      run: make vet
    - name: Fuzz
      run: make fuzz
    - name: Benchmark
      run: make benchmark
